-- Database schema for Distributed Online Examination System
-- Demonstrates ACID properties and distributed state management

CREATE TABLE IF NOT EXISTS students (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  is_admin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS exams (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) UNIQUE NOT NULL,
  description TEXT,
  duration_seconds INTEGER NOT NULL DEFAULT 3600,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS questions (
  id SERIAL PRIMARY KEY,
  exam_id INTEGER REFERENCES exams(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option CHAR(1) NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D'))
);

CREATE TABLE IF NOT EXISTS submissions (
  id SERIAL PRIMARY KEY,
  student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
  exam_id INTEGER REFERENCES exams(id) ON DELETE CASCADE,
  answers JSONB NOT NULL,
  score INTEGER,
  total_questions INTEGER,
  submitted_at TIMESTAMP DEFAULT NOW(),
  graded_at TIMESTAMP,
  node_id VARCHAR(10),
  UNIQUE(student_id, exam_id)
);

CREATE TABLE IF NOT EXISTS exam_sessions (
  id SERIAL PRIMARY KEY,
  student_id INTEGER REFERENCES students(id) ON DELETE CASCADE,
  exam_id INTEGER REFERENCES exams(id) ON DELETE CASCADE,
  started_at TIMESTAMP DEFAULT NOW(),
  node_id VARCHAR(10),
  session_key VARCHAR(255) UNIQUE NOT NULL
);

-- Create indices for performance (IF NOT EXISTS for idempotent multi-node init)
CREATE INDEX IF NOT EXISTS idx_questions_exam_id ON questions(exam_id);
CREATE INDEX IF NOT EXISTS idx_submissions_student_id ON submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_submissions_exam_id ON submissions(exam_id);
CREATE INDEX IF NOT EXISTS idx_submissions_created ON submissions(submitted_at);
CREATE INDEX IF NOT EXISTS idx_exam_sessions_student ON exam_sessions(student_id);
CREATE INDEX IF NOT EXISTS idx_exam_sessions_session ON exam_sessions(session_key);

-- Add is_admin column if upgrading from previous schema
ALTER TABLE students ADD COLUMN IF NOT EXISTS is_admin BOOLEAN DEFAULT FALSE;

-- Seed sample students (password: test123)
-- Using bcrypt hash of "test123"
INSERT INTO students (username, password_hash, is_admin) VALUES
  ('student1', '$2a$10$djyLfCU46NLjrA2aaye19uKxeOV6urGW1SkD.F0tacX.tcdgv/T5i', TRUE),
  ('student2', '$2a$10$djyLfCU46NLjrA2aaye19uKxeOV6urGW1SkD.F0tacX.tcdgv/T5i', FALSE),
  ('student3', '$2a$10$djyLfCU46NLjrA2aaye19uKxeOV6urGW1SkD.F0tacX.tcdgv/T5i', FALSE)
ON CONFLICT (username) DO UPDATE SET is_admin = EXCLUDED.is_admin;

-- Seed exams
INSERT INTO exams (title, description, duration_seconds) VALUES
  ('Parallel & Distributed Computing Midterm',
   'A comprehensive exam covering fundamental PDC concepts including parallelism, distribution, fault tolerance, and load balancing.',
   1800)
ON CONFLICT DO NOTHING;

INSERT INTO exams (title, description, duration_seconds) VALUES
  ('Data Structures & Algorithms',
   'Test your knowledge of fundamental data structures and algorithmic paradigms including trees, graphs, sorting, and dynamic programming.',
   1800)
ON CONFLICT DO NOTHING;

INSERT INTO exams (title, description, duration_seconds) VALUES
  ('Operating Systems',
   'Covers process management, memory management, file systems, and concurrency in modern operating systems.',
   1800)
ON CONFLICT DO NOTHING;

INSERT INTO exams (title, description, duration_seconds) VALUES
  ('Computer Networks',
   'Examines network layers, protocols, routing, and security fundamentals in distributed communication.',
   1800)
ON CONFLICT DO NOTHING;

INSERT INTO exams (title, description, duration_seconds) VALUES
  ('Database Management Systems',
   'Assesses understanding of relational databases, SQL, normalization, transactions, and query optimization.',
   1800)
ON CONFLICT DO NOTHING;

-- Seed questions for Exam 1: PDC
INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
  (1,
   'What is the primary advantage of distributed computing?',
   'Reduced cost',
   'Improved fault tolerance and scalability',
   'Simpler code',
   'Faster single-thread performance',
   'B'),
  (1,
   'Which of the following is a distributed state management tool?',
   'Docker',
   'Redis',
   'Nginx',
   'PostgreSQL',
   'B'),
  (1,
   'What does the fork-join model represent in parallel computing?',
   'Network topology',
   'Database design',
   'Task decomposition and synchronization',
   'Load balancing algorithm',
   'C'),
  (1,
   'In load balancing, what does least-conn algorithm do?',
   'Routes to the server with lowest latency',
   'Routes to the server with fewest active connections',
   'Routes randomly',
   'Routes always to the first server',
   'B'),
  (1,
   'What is a key characteristic of fault-tolerant systems?',
   'No failures ever occur',
   'System continues operation despite component failures',
   'All data is stored in memory',
   'Single point of control',
   'B'),
  (1,
   'How does a message queue like Bull improve system reliability?',
   'By encrypting all data',
   'By preventing data loss during peak load',
   'By removing the need for databases',
   'By allowing offline operation',
   'B'),
  (1,
   'What does Socket.IO provide in distributed systems?',
   'Database persistence',
   'Real-time bidirectional communication',
   'File storage',
   'Code compilation',
   'B'),
  (1,
   'Which PDC concept does a load balancer primarily demonstrate?',
   'Data parallelism',
   'Work distribution across resources',
   'Data persistence',
   'Authentication',
   'B'),
  (1,
   'What is the purpose of a distributed timer in exam systems?',
   'To measure server performance',
   'To prevent cheating by synchronizing time across all nodes',
   'To reduce database queries',
   'To improve network speed',
   'B'),
  (1,
   'In the context of parallel computing, what are worker threads used for?',
   'Managing network connections',
   'Processing multiple tasks simultaneously',
   'Storing data',
   'Monitoring system health',
   'B')
ON CONFLICT DO NOTHING;

-- Seed questions for Exam 2: DSA
INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
  (2,
   'What is the time complexity of binary search on a sorted array?',
   'O(n)',
   'O(log n)',
   'O(n^2)',
   'O(1)',
   'B'),
  (2,
   'Which data structure uses LIFO (Last In First Out) principle?',
   'Queue',
   'Stack',
   'Linked List',
   'Tree',
   'B'),
  (2,
   'What is a hash table''s average time complexity for lookups?',
   'O(n)',
   'O(1)',
   'O(log n)',
   'O(n^2)',
   'B'),
  (2,
   'Which algorithm is used to find the shortest path in a weighted graph?',
   'Breadth-First Search',
   'Dijkstra''s algorithm',
   'QuickSort',
   'Merge Sort',
   'B'),
  (2,
   'What property makes a binary search tree valid?',
   'Root is always the largest',
   'Left child < parent < right child',
   'All leaves are at same depth',
   'Each node has exactly two children',
   'B'),
  (2,
   'Which sorting algorithm has the best worst-case time complexity?',
   'Bubble Sort',
   'Merge Sort',
   'Quick Sort',
   'Selection Sort',
   'B'),
  (2,
   'What is a priority queue typically implemented with?',
   'Array',
   'Heap',
   'Linked List',
   'Hash Table',
   'B'),
  (2,
   'What does DFS stand for in graph traversal?',
   'Direct Fast Search',
   'Depth-First Search',
   'Data Format Standard',
   'Distributed File System',
   'B'),
  (2,
   'Which data structure is optimal for implementing a breadth-first search?',
   'Stack',
   'Queue',
   'Array',
   'Hash Set',
   'B'),
  (2,
   'What is the space complexity of merge sort?',
   'O(1)',
   'O(n)',
   'O(log n)',
   'O(n^2)',
   'B')
ON CONFLICT DO NOTHING;

-- Seed questions for Exam 3: OS
INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
  (3,
   'What is a process in operating systems?',
   'A file being read',
   'A program in execution',
   'A memory address',
   'A system call',
   'B'),
  (3,
   'Which scheduling algorithm assigns the CPU to the process with the smallest execution time?',
   'Round Robin',
   'Shortest Job First',
   'First Come First Serve',
   'Priority Scheduling',
   'B'),
  (3,
   'What is a deadlock in operating systems?',
   'A system crash',
   'Two or more processes waiting indefinitely for resources held by each other',
   'A memory leak',
   'An invalid system call',
   'B'),
  (3,
   'Which memory management scheme allows processes to be larger than physical memory?',
   'Paging',
   'Virtual memory',
   'Segmentation',
   'Fixed partitioning',
   'B'),
  (3,
   'What is a mutex used for?',
   'Monitoring CPU usage',
   'Mutual exclusion in concurrent programming',
   'Managing files',
   'Network communication',
   'B'),
  (3,
   'What is the role of a system call interface?',
   'Direct hardware access',
   'Bridge between user space and kernel space',
   'File compression',
   'Process creation only',
   'B'),
  (3,
   'Which page replacement algorithm replaces the page that will not be used for the longest time?',
   'FIFO',
   'Optimal Page Replacement',
   'LRU',
   'Clock Algorithm',
   'B'),
  (3,
   'What is a race condition?',
   'A hardware malfunction',
   'Multiple threads accessing shared data without synchronization',
   'Network latency',
   'Disk fragmentation',
   'B'),
  (3,
   'What does a semaphore with count N allow?',
   'N processes to run simultaneously',
   'Up to N processes to access a resource concurrently',
   'N interrupts per second',
   'N files to be open',
   'B'),
  (3,
   'In the context of threads, what is concurrency?',
   'Running on multiple CPUs at once',
   'Multiple threads making progress in overlapping time periods',
   'Single-thread execution',
   'Parallel hardware',
   'B')
ON CONFLICT DO NOTHING;

-- Seed questions for Exam 4: Networks
INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
  (4,
   'Which layer of the OSI model handles routing?',
   'Data Link Layer',
   'Network Layer',
   'Transport Layer',
   'Application Layer',
   'B'),
  (4,
   'What protocol is used for reliable data delivery?',
   'UDP',
   'TCP',
   'IP',
   'HTTP',
   'B'),
  (4,
   'What is a subnet mask used for?',
   'Encrypting data packets',
   'Determining network and host portions of an IP address',
   'Compressing network traffic',
   'Assigning IP addresses dynamically',
   'B'),
  (4,
   'What does DNS stand for?',
   'Data Network System',
   'Domain Name System',
   'Digital Network Service',
   'Dynamic Node Switching',
   'B'),
  (4,
   'Which protocol is used for secure web browsing?',
   'HTTP',
   'HTTPS',
   'FTP',
   'SMTP',
   'B'),
  (4,
   'What is the maximum hop count in OSPF?',
   '15',
   'No fixed limit (uses cost metric)',
   '32',
   '64',
   'B'),
  (4,
   'What does a MAC address identify?',
   'A network connection globally',
   'A network interface controller uniquely',
   'An IP address',
   'A web domain',
   'B'),
  (4,
   'What is the purpose of a firewall?',
   'Speed up network traffic',
   'Filter incoming and outgoing network traffic based on security rules',
   'Assign IP addresses',
   'Route packets between networks',
   'B'),
  (4,
   'Which protocol is used for sending emails?',
   'HTTP',
   'SMTP',
   'FTP',
   'TCP',
   'B'),
  (4,
   'What is latency in networking?',
   'Bandwidth capacity',
   'Time delay in data transmission',
   'Data packet size',
   'Network protocol version',
   'B')
ON CONFLICT DO NOTHING;

-- Seed questions for Exam 5: DBMS
INSERT INTO questions (exam_id, question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
  (5,
   'What is a primary key in a relational database?',
   'The first column in a table',
   'A unique identifier for each row in a table',
   'A foreign table reference',
   'An indexed column',
   'B'),
  (5,
   'What does SQL stand for?',
   'Simple Query Language',
   'Structured Query Language',
   'Standard Question Language',
   'Sequential Query Logic',
   'B'),
  (5,
   'What is database normalization?',
   'Making databases run faster',
   'Organizing data to reduce redundancy and dependency',
   'Compressing database files',
   'Encrypting sensitive data',
   'B'),
  (5,
   'What is an ACID property in transactions?',
   'A hardware requirement',
   'Atomicity, Consistency, Isolation, Durability',
   'A programming language',
   'A network protocol',
   'B'),
  (5,
   'What does a JOIN operation do in SQL?',
   'Deletes a table',
   'Combines rows from two or more tables based on related columns',
   'Creates a new database',
   'Updates existing records',
   'B'),
  (5,
   'What is a foreign key?',
   'A key for encryption',
   'A field that references the primary key of another table',
   'The main key of a table',
   'An alternate key',
   'B'),
  (5,
   'What is an index in database?',
   'A table constraint',
   'A data structure that speeds up data retrieval',
   'A type of query',
   'A backup file',
   'B'),
  (5,
   'What is a transaction in DBMS?',
   'A user login event',
   'A sequence of operations performed as a single logical unit of work',
   'A database backup',
   'A network request',
   'B'),
  (5,
   'What does the GROUP BY clause do?',
   'Sorts query results',
   'Groups rows with same values into summary rows',
   'Filters rows based on conditions',
   'Joins two tables',
   'B'),
  (5,
   'What is the purpose of a view in SQL?',
   'To store data permanently',
   'To provide a virtual table based on a query result',
   'To index a table',
   'To enforce referential integrity',
   'B')
ON CONFLICT DO NOTHING;

-- Update student1 as admin (in case already exists)
UPDATE students SET is_admin = TRUE WHERE username = 'student1';
